### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by oxdc** [tamuhey/tokenizations#37]
I tried to install pytokenizations on aarch64 platform with Python 3.6 and pip installed, it threw:

```
Collecting pytokenizations
  Downloading https://files.pythonhosted.org/packages/*******/pytokenizations-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-********/pytokenizations/setup.py'
```

Is there any way to resolve?

**Comment by tamuhey** [comment]
Hi, thanks for reporting issue!
Please try `pip install -U pip` and install pytokenizations again

**Comment by oxdc** [comment]
thanks a lot! I finally resolved it.
